- name: Установка пакета httpd
  become: yes
  apt:
    name: apache2
    state: present

- name: Включение сервиса httpd
  become: yes
  service:
    name: apache2
    state: started
    enabled: true