- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Check if AWS CLI package is already downloaded
  become: true
  stat:
    path: /tmp/awscliv2.zip
  register: aws_cli_pkg_status
  changed_when: false

- name: Download AWS CLI package
  become: true
  shell: "curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip'"
  args:
    chdir: /tmp
  when: not aws_cli_pkg_status.stat.exists

- name: Unzip AWS CLI package
  become: true
  shell: "unzip awscliv2.zip"
  args:
    chdir: /tmp
  when: not aws_cli_pkg_status.stat.exists

- name: Install AWS CLI
  become: true
  shell: "sudo /tmp/aws/install"
  args:
    chdir: /tmp
  when: not aws_cli_pkg_status.stat.exists

- name: Run exit command
  become: true
  ansible.builtin.shell: exit
