- name: Update apt cache
  become: true
  apt:
    update_cache: "yes"
- name: Install ClamAV
  become: true
  apt:
    name:
      - clamav
      - clamav-daemon
    state: present

- name: Stop ClamAV service
  become: true
  service:
    name: clamav-freshclam
    state: stopped

- name: Update the ClamAV signature database
  become: true
  command: freshclam

- name: Configure ClamAV user
  become: true
  replace:
    path: /etc/systemd/system/multi-user.target.wants/clamav-daemon.service
    regexp: ^User=clamav
    replace: User=root

- name: Restart ClamAV service
  become: true
  service:
    name: clamav-freshclam
    state: restarted
    enabled: true

- name: Start ClamAV service
  become: true
  service:
    name: clamav-freshclam
    state: started
    enabled: true

- name: Enable ClamAV daemon
  become: true
  service:
    name: clamav-daemon
    enabled: "yes"
