- name: Check if ClamAV is installed
  become: true
  command: dpkg -s clamav
  register: clamav_package_status
  changed_when: false
  failed_when: false

- name: Install ClamAV
  become: true
  apt:
    name:
      - clamav
      - clamav-daemon
    state: present
  when: clamav_package_status.rc != 0

- name: Update apt cache
  become: true
  apt:
    update_cache: "yes"
  when: clamav_package_status.rc != 0

- name: Install ClamAV
  become: true
  apt:
    name:
      - clamav
      - clamav-daemon
    state: present
  when: clamav_package_status.rc != 0

- name: Stop ClamAV service
  become: true
  service:
    name: clamav-freshclam
    state: stopped
  when: clamav_package_status.rc != 0

- name: read clamav config file
  become: true
  vars:
    clamav_config_file: /etc/clamav/clamd.conf
    scan_directory: /user/ubuntu/
  lineinfile:
    path: "{{ clamav_config_file }}"
    regexp: "^#OnAccessIncludePath"
    line: "OnAccessIncludePath {{ scan_directory }}"
    state: present
    backup: "yes"
  when: clamav_package_status.rc != 0

- name: Add OnAccessPrevention line
  become: true
  vars:
    clamav_config_file: /etc/clamav/clamd.conf
  blockinfile:
    path: "{{ clamav_config_file }}"
    block: |
      ScanOnAccess yes
      OnAccessPrevention yes
    backup: "yes"
  when: clamav_package_status.rc != 0

- name: Update the ClamAV signature database
  become: true
  command: freshclam
  when: clamav_package_status.rc != 0

- name: Add User=clamav line to clamav-daemon.service
  become: true
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/clamav-daemon.service
    line: "User=root"
    insertafter: '\[Service\]'
  when: clamav_package_status.rc != 0

- name: Restart ClamAV service
  become: true
  service:
    name: clamav-freshclam
    state: restarted
    enabled: true
  when: clamav_package_status.rc != 0

- name: Start ClamAV service
  become: true
  service:
    name: clamav-freshclam
    state: started
    enabled: true
  when: clamav_package_status.rc != 0

- name: Enable ClamAV daemon
  become: true
  service:
    name: clamav-daemon
    enabled: true
  when: clamav_package_status.rc != 0
