- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install prerequisites
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  register: add_docker_key
  changed_when: false

- name: Add Docker repository
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    create: yes

- name: Update apt cache again
  become: true
  apt:
    update_cache: yes

- name: Check Docker package policy
  become: true
  command: apt-cache policy docker-ce
  register: docker_package_policy

- name: Install Docker
  become: true
  apt:
    name: docker-ce
    state: present
  when: "'Installed: (none)' in docker_package_policy.stdout_lines[1]"
