- name: Package installation
  hosts: prod
  become: true
  roles:
    #  - ClamAV
    #  - Docker
    - role: Java_JDK
      when: not jdk_installed # assuming jdk_installed is a variable defined earlier
    - role: AWS_SLI #this block should be the last one. It contains a stop command, after which tasks are not executed
      when: not aws_sli_installed
